//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ShopFlower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIENHE
    {
        public string MALH { get; set; }
        
        [Required(ErrorMessage = "Vui lòng nhập họ tên")]
        [StringLength(100, ErrorMessage = "Họ tên không được quá 100 ký tự")]
        public string HOTEN { get; set; }
        
        [Required(ErrorMessage = "Vui lòng nhập email")]
        [EmailAddress(ErrorMessage = "Email không hợp lệ")]
        public string EMAIL { get; set; }
        
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        [RegularExpression(@"^0[0-9]{9}$", ErrorMessage = "Số điện thoại không hợp lệ (10 số, bắt đầu bằng 0)")]
        public string DIENTHOAI { get; set; }
        
        [Required(ErrorMessage = "Vui lòng nhập nội dung")]
        [StringLength(1000, ErrorMessage = "Nội dung không được quá 1000 ký tự")]
        public string NOIDUNG { get; set; }
    }
}
