//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShopFlower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIENHE
    {
        public string MALH { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập họ và tên")]
        [StringLength(100, ErrorMessage = "Họ tên không được vượt quá 100 ký tự")]
        [Display(Name = "Họ và tên")]
        public string HOTEN { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập email")]
        [EmailAddress(ErrorMessage = "Email không hợp lệ")]
        [Display(Name = "Email")]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        [RegularExpression(@"^0\d{9}$", ErrorMessage = "Số điện thoại phải có 10 số và bắt đầu bằng số 0")]
        [Display(Name = "Điện thoại")]
        public string DIENTHOAI { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập nội dung")]
        [StringLength(500, ErrorMessage = "Nội dung không được vượt quá 500 ký tự")]
        [Display(Name = "Nội dung")]
        public string NOIDUNG { get; set; }
    }
}
