//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopFlower.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_SHOPFLOWEREntities : DbContext
    {
        public QL_SHOPFLOWEREntities()
            : base("name=QL_SHOPFLOWEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOAIHANG> LOAIHANGs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
    }
}
