//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopFlower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public string AnhSP { get; set; }
        public string MoTaSP { get; set; }
        public string TinhTrang { get; set; }
        public string ThuongHieu { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string MaLoai { get; set; }
    
        public virtual LOAIHANG LOAIHANG { get; set; }
    }
}
