

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShopFlower.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class QL_SHOPFLOWEREntities : DbContext
{
    public QL_SHOPFLOWEREntities()
        : base("name=QL_SHOPFLOWEREntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<LOAIHANG> LOAIHANGs { get; set; }

    public virtual DbSet<SANPHAM> SANPHAMs { get; set; }

    public virtual DbSet<LIENHE> LIENHEs { get; set; }

    public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }

    public virtual DbSet<TAIKHOAN_VAITRO> TAIKHOAN_VAITRO { get; set; }

    public virtual DbSet<VAITRO> VAITROes { get; set; }

    public virtual DbSet<CTHD> CTHDs { get; set; }

    public virtual DbSet<HOADON> HOADONs { get; set; }

    public virtual DbSet<TINTUC> TINTUCs { get; set; }


    public virtual ObjectResult<SearchProducts_Result> SearchProducts(string keyword)
    {

        var keywordParameter = keyword != null ?
            new ObjectParameter("Keyword", keyword) :
            new ObjectParameter("Keyword", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchProducts_Result>("SearchProducts", keywordParameter);
    }


    public virtual ObjectResult<sp_LayDanhSachLienHe_Result> sp_LayDanhSachLienHe(Nullable<int> pageNumber, Nullable<int> pageSize)
    {

        var pageNumberParameter = pageNumber.HasValue ?
            new ObjectParameter("PageNumber", pageNumber) :
            new ObjectParameter("PageNumber", typeof(int));


        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("PageSize", pageSize) :
            new ObjectParameter("PageSize", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachLienHe_Result>("sp_LayDanhSachLienHe", pageNumberParameter, pageSizeParameter);
    }


    public virtual int sp_ThemLienHe(string hoTen, string email, string dienThoai, string noiDung, ObjectParameter maLH)
    {

        var hoTenParameter = hoTen != null ?
            new ObjectParameter("HoTen", hoTen) :
            new ObjectParameter("HoTen", typeof(string));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        var dienThoaiParameter = dienThoai != null ?
            new ObjectParameter("DienThoai", dienThoai) :
            new ObjectParameter("DienThoai", typeof(string));


        var noiDungParameter = noiDung != null ?
            new ObjectParameter("NoiDung", noiDung) :
            new ObjectParameter("NoiDung", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLienHe", hoTenParameter, emailParameter, dienThoaiParameter, noiDungParameter, maLH);
    }


    public virtual ObjectResult<string> sp_GetRolesByUser(string userName)
    {

        var userNameParameter = userName != null ?
            new ObjectParameter("UserName", userName) :
            new ObjectParameter("UserName", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetRolesByUser", userNameParameter);
    }


    public virtual ObjectResult<Nullable<int>> sp_ValidateUser(string userName, string password)
    {

        var userNameParameter = userName != null ?
            new ObjectParameter("UserName", userName) :
            new ObjectParameter("UserName", typeof(string));


        var passwordParameter = password != null ?
            new ObjectParameter("Password", password) :
            new ObjectParameter("Password", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ValidateUser", userNameParameter, passwordParameter);
    }


    public virtual ObjectResult<string> sp_LayVaiTroTheoNguoiDung(string tenDangNhap)
    {

        var tenDangNhapParameter = tenDangNhap != null ?
            new ObjectParameter("TenDangNhap", tenDangNhap) :
            new ObjectParameter("TenDangNhap", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_LayVaiTroTheoNguoiDung", tenDangNhapParameter);
    }


    public virtual ObjectResult<Nullable<int>> sp_XacThucTaiKhoan(string tenDangNhap, string matKhau)
    {

        var tenDangNhapParameter = tenDangNhap != null ?
            new ObjectParameter("TenDangNhap", tenDangNhap) :
            new ObjectParameter("TenDangNhap", typeof(string));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_XacThucTaiKhoan", tenDangNhapParameter, matKhauParameter);
    }

}

}

