//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopFlower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN_VAITRO
    {
        public int Id { get; set; }
        public int MaTK { get; set; }
        public int MaVaiTro { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
